import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './styles.css'
import './enhancements.css'
import './pet.css'
import './reference-ui.css'
import './scene.css'
import './interaction.css'
import './module-ui.css'
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
